INSERT INTO product (product_name , total_units, cost) VALUES ('Sofa', 160, 200.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Love Seat', 160, 100.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Sectional', 100, 300.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Table', 200, 200.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Recliner', 200, 150.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Mattress', 250, 200.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Pillow', 400, 10.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Ottoman', 150, 25.00);
INSERT INTO product (product_name , total_units, cost) VALUES ('Desk', 100, 75.00);
INSERT INTO customer (customer_first_name , customer_last_name, customer_phone, customer_email) VALUES ('Nancy', 'Hanson', '508-678-0654', 'n.hanson@gmail.com');
INSERT INTO store (store_name, store_location, store_phone) VALUES ('South Idaho', 'Boise, ID', '208-319-0756');
INSERT INTO store_customer (customer_id, store_id) VALUES (1,1);